version: "3.6"
services:

        reverse-proxy:
                image: nginx:stable
                container_name: reverse-proxy_1
                depends_on:
                        - web-server
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./reverse-proxy/conf.d/mysite.template:/etc/nginx/conf.d/mysite.template
                        - ./reverse-proxy/html:/usr/share/nginx/html:ro
                environment:
                        - NGINX_HOST=reverseproxy.com
                        - NGINX_PORT=80
                command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"


        web-server:
                image: nginx:stable
                volumes:
                        - ./web-server/html:/usr/share/nginx/html:ro
                        - ./web-server/conf.d/mysite.template:/etc/nginx/conf.d/mysite.template
                container_name: web-server_1
                ports:
                        - "8081:80"
                        - "4443:443"
                environment:
                        - NGINX_HOST=webserver.com
                        - NGINX_PORT=80
                command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
