version: "3.6"
services:
        reverseproxy:
                image: nginx:stable
                container_name: reverseproxy_1
                depends_on:
                        - webserver
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ../reverseproxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
                        - ../reverseproxy/html:/usr/share/nginx/html:ro
                networks:
                        - ngnixtonginx

        webserver:
                image: nginx:stable
                volumes:
                        - ../webserver/html:/usr/share/nginx/html:ro
                        - ../webserver/conf.d/default.conf:/etc/nginx/conf.d/default.conf
                container_name: webserver_1
                ports:
                        - "8081:80"
                        - "4443:443"
                networks:
                        - ngnixtonginx

networks:
        ngnixtonginx:
                driver: bridge
                name: ngnixtonginx
